version: 2.1
executors:
  macos-executor:
    macos:
      xcode: "15.3.0"
    resource_class: macos.m1.medium
    working_directory: ~/project
jobs:
  ios-build:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Install Ruby dependencies (Fastlane)
          command: bundle install
      - run:
          name: Run Fastlane build
          command: bundle exec fastlane build # Replace 'build' with your lane name if different
      - store_artifacts:
          path: ~/Library/Developer/Xcode/Archives
          destination: ios-archives
workflows:
  build-ios:
    jobs:
      - ios-build